### ISSUE TITLE
Crashing App in Unit Tests due to TypeError

### ISSUE THREAD

**Issue by seanmcquaid** [bugsnag/bugsnag-js-performance#345]
### Describe the bug
Any unit tests I have are crashing when utilizing the 'bugsnag/browser-performance' library due to the following error : 

TypeError: Cannot read properties of undefined (reading 'loadEventEnd')

### Steps to reproduce
1. Add 'bugsnag/browser-performance' to a project
2. Add the import to a function that has a unit test
3. Run the unit test
4. Notice that you will get the TypeError from above.

### Environment
* BugSnag Performance library version: 1.1.0
* BugSnag Error Monitoring library version (if any): 7.20.2
* Browser framework version (if any):
    * Vue:
    * React: 18.2
    * Angular:
* Server framework version (if any):
    * Koa:
    * Express:
    * Restify:
* Browser version (e.g. chrome, safari): Chrome
* Device (e.g. iphonex):

**Comment by mclack** [comment]
Hi @seanmcquaid

As a note to begin with, [@bugsnag/browser-performance](https://www.npmjs.com/package/@bugsnag/browser-performance) is entirely based around browser APIs, so we would not expect this to work within a Node-like environment. If you do want to run BugSnag Performance in your unit tests, you would need to make sure you're using something like [jsdom](https://www.npmjs.com/package/jsdom) so that browser APIs exist ([Jest](https://www.npmjs.com/package/jest) has this built in by default).

Generally speaking, we would not recommend running BugSnag Performance in unit tests, as this would reduce the performance of your tests. We'd instead recommend mocking your unit tests, using something like [Jest's module mocking](https://jestjs.io/docs/mock-functions#mocking-modules). If you want to utilise our Performance library for your unit tests, would you be able to provide some insight into what you'd hope to achieve with this, and the value it would provide?

If you're confident that the sufficient browser APIs are available, would you be able to provide some more information for our further investigation? It would be particularly useful to know which unit testing framework you are using. If you're also able to supply any code snippets/screenshots or examples of how you are running your unit tests and triggering this error, as well as a full stack trace of the error, this would also be very helpful in trying to reproduce this for ourselves and make necessary changes to our code.

As this is a public thread, you may prefer to open a ticket with us directly by reaching out to support@bugsnag.com and referencing this issue: https://github.com/bugsnag/bugsnag-js-performance/issues/345

**Comment by seanmcquaid** [comment]
> Hi @seanmcquaid
> 
> 
> 
> As a note to begin with, [@bugsnag/browser-performance](https://www.npmjs.com/package/@bugsnag/browser-performance) is entirely based around browser APIs, so we would not expect this to work within a Node-like environment. If you do want to run BugSnag Performance in your unit tests, you would need to make sure you're using something like [jsdom](https://www.npmjs.com/package/jsdom) so that browser APIs exist ([Jest](https://www.npmjs.com/package/jest) has this built in by default).
> 
> 
> 
> Generally speaking, we would not recommend running BugSnag Performance in unit tests, as this would reduce the performance of your tests. We'd instead recommend mocking your unit tests, using something like [Jest's module mocking](https://jestjs.io/docs/mock-functions#mocking-modules). If you want to utilise our Performance library for your unit tests, would you be able to provide some insight into what you'd hope to achieve with this, and the value it would provide?
> 
> 
> 
> If you're confident that the sufficient browser APIs are available, would you be able to provide some more information for our further investigation? It would be particularly useful to know which unit testing framework you are using. If you're also able to supply any code snippets/screenshots or examples of how you are running your unit tests and triggering this error, as well as a full stack trace of the error, this would also be very helpful in trying to reproduce this for ourselves and make necessary changes to our code.
> 
> 
> 
> As this is a public thread, you may prefer to open a ticket with us directly by reaching out to support@bugsnag.com and referencing this issue: https://github.com/bugsnag/bugsnag-js-performance/issues/345

Totally understand that! I should've added this to the original issue but this was occurring even after mocking the module appropriately. I'll probably open a ticket for this with y'all.

**Comment by clr182** [comment]
Hi @seanmcquaid  
I'm going to close this ticket out for now but please feel free to reopen it if you have gather more information.
