### ISSUE TITLE
pod install Invalid `Podfile` file: Invalid `BugsnagReactNativePerformance.podspec` file: undefined method `install_modules_dependencies' for Pod:Module Did you mean?  install_flipper_dependencies.

### ISSUE THREAD

**Issue by ste00martin** [bugsnag/bugsnag-js-performance#358]
### Describe the bug
When running `pod install` I get the following error
```
[!] Invalid `Podfile` file:
[!] Invalid `BugsnagReactNativePerformance.podspec` file: undefined method `install_modules_dependencies' for Pod:Module
Did you mean?  install_flipper_dependencies.
```

### Steps to reproduce
on react native version 0.70.8:
install bugsnag-performance version 1.3.0
npm install
pod install --project-directory='./ios'

### Environment
* BugSnag Performance library version:  1.3.0
* BugSnag Error Monitoring library version (if any):     "@bugsnag/react-native": "^7.18.2",

**Comment by clr182** [comment]
Hi @ste00martin 
Our performance-js SDK is only compatible with react native **v0.71+**. You are likely seeing these errors as you are using an older version of react native (**v0.70.8**). we recommend [upgrading](https://reactnative.dev/docs/upgrading) to at least **v0.71** in order to utilize our performance SDK. I'm going to close this ticket out now as solved, but If after upgrading version you are still having issues then please let us know and we'd be happy to help.
